prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix cco: <http://purl.org/ontology/cco/core#>
prefix pair: <http://virtual-assembly.org/pair_v2#>

# DELETE { GRAPH <file:///home/jmv/data/Non_public/Voisins-sur-site.csv.split.ttl> {?ORGA ?P ?O .}}
INSERT { GRAPH ?newURI {
  ?PERSON a foaf:Person ;
          foaf:familyName ?FN ;
          foaf:givenName ?GN ;
          foaf:mbox ?MB ;
          foaf:phone ?PH .

  ?newURI a foaf:Organization .
  ?newURI ?P ?O .
  ?newURI pair:hasResponsible ?ORGA .
}}
WHERE { GRAPH <file:///home/jmv/data/Non_public/Voisins-sur-site.csv.split.ttl> {
 OPTIONAL {
  ?PERSON foaf:familyName ?FN ;
          foaf:givenName ?GN ;
          foaf:mbox ?MB ;
          foaf:phone ?PH . }

 OPTIONAL {
  ?ORGA  a <http://vocab.sindice.net/csv/Row> ;
         ?P ?O .
  FILTER( ?P != foaf:familyName &&
          ?P != foaf:givenName &&
          ?P != foaf:mbox &&
          ?P != foaf:phone &&
          ?P != <http://vocab.sindice.net/csv/row>
   )
 }
 BIND (URI(CONCAT( STR(?ORGA), "-org") ) AS ?newURI)
}}
